name: unpub_aws
description: A collection of modules to use for deploying unpub into AWS infrastructure.
version: 0.1.1
homepage: https://github.com/bytedance/unpub
publish_to: none
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  unpub:
    git:
      url: https://github.com/luansilva-tokenlab/unpub
      path: unpub
  minio: ^3.5.0
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  chunked_stream: ^1.4.2
  mockito: ^5.4.4
  build_runner: ^2.4.8
  path: ^1.9.0
  json_annotation: ^4.8.1

dependency_overrides:
  http: ^1.2.1
  intl: ^0.18.0
#   unpub:
#     path: ../unpub
