name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information.
version: 2.0.2
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=3.0.0 <4.0.0"
publish_to: none

executables:
  unpub: unpub

dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http_parser: ^4.0.2
  http: ^1.2.1
  archive: ^3.4.10
  logging: ^1.2.0
  meta: ^1.12.0
  googleapis: ^13.0.0
  yaml: ^3.1.2
  pub_semver: ^2.1.4
  json_annotation: ^4.8.1
  mongo_dart: ^0.10.0
  mime: ^1.0.5
  intl: ^0.18.0
  path: ^1.9.0
  collection: ^1.18.0
  shelf_cors_headers: ^0.1.5
dev_dependencies:
  test: ^1.25.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  shelf_router_generator: ^1.1.0
  chunked_stream: ^1.4.2
